# 02 — Pré-processamento

**Dimensão 4 da rúbrica — 15 pontos.**

In [1]:
#Importação de bibliotecas
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Semente fixa: use em TODO ponto com aleatoriedade (split, modelos, CV).
RANDOM_STATE = 42

In [2]:
#Leitura dos arquivos processados no notebook 1 e salvos no Github
import pandas as pd
import numpy as np

url_base_credito = f"https://github.com/camilavbr/Tech_Challenge_Fase2_rm377839/raw/main/data/processed/base_credito.csv"
url_base_credito_faixas = f"https://github.com/camilavbr/Tech_Challenge_Fase2_rm377839/raw/main/data/processed/base_credito_faixas.csv"

base_credito = pd.read_csv(url_base_credito)
base_credito_faixas = pd.read_csv(url_base_credito_faixas)

In [3]:
#Visualização dos dados
base_credito.head()

,ID,GENERO,CARRO_PROPRIO,IMOVEIS,FILHOS,RENDA,TIPO_OCUPACAO,ESCOLARIDADE,ESTADO_CIVIL,TIPO_RESIDENCIA,TELEFONE_TRABALHO,TELEFONE,EMAIL,MEMBROS_FAMILIA,mau_pagador,IDADE,ANOS_EMPREGADO,STATUS_EMPREGO
0,5008804,1,1,1,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,0,0,2.0,0,32,12.435318,Empregado
1,5008805,1,1,1,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,0,0,2.0,0,32,12.435318,Empregado
2,5008806,1,1,1,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,0,0,0,2.0,0,58,3.104723,Empregado
3,5008808,0,0,1,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1,1,1.0,0,52,8.353183,Empregado
4,5008809,0,0,1,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1,1,1.0,0,52,8.353183,Empregado

In [4]:
#Visualização dos dados por faixa
base_credito_faixas.head()

,ID,GENERO,CARRO_PROPRIO,IMOVEIS,FILHOS,TIPO_OCUPACAO,ESCOLARIDADE,ESTADO_CIVIL,TIPO_RESIDENCIA,TELEFONE_TRABALHO,TELEFONE,EMAIL,MEMBROS_FAMILIA,mau_pagador,FAIXA_ETARIA,FAIXA_EMPREGO,FAIXA_RENDA
0,5008804,1,1,1,0,Working,Higher education,Civil marriage,Rented apartment,1,0,0,2.0,0,25 a 34 anos,Mais de 7 anos,Renda Alta
1,5008805,1,1,1,0,Working,Higher education,Civil marriage,Rented apartment,1,0,0,2.0,0,25 a 34 anos,Mais de 7 anos,Renda Alta
2,5008806,1,1,1,0,Working,Secondary / secondary special,Married,House / apartment,0,0,0,2.0,0,50 a 64 anos,3 a 7 anos,Renda Baixa
3,5008808,0,0,1,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1,1,1.0,0,50 a 64 anos,Mais de 7 anos,Renda Alta
4,5008809,0,0,1,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1,1,1.0,0,50 a 64 anos,Mais de 7 anos,Renda Alta

## 1. Dados faltantes

In [7]:
nulos = base_credito.isna().sum()
pd.DataFrame({"nulos": nulos, "pct": (nulos / len(base_credito) * 100).round(2)}).query("nulos > 0")

Empty DataFrame
Columns: [nulos, pct]
Index: []

**Decisão:**

Foram identificados nulos na base original no notebook 1 na coluna OCUPATION_TYPE, porém foi decidido não trabalhar com esta coluna e sim com a NAME_INCOME_TYPE que já realizava um agrupamento dos tipos de ocupação.

## 2. Definição da variável alvo

A variável alvo foi consolidada em formato binário: 0 para Bons Pagadores e 1 para Maus Pagadores. O limiar de corte escolhido foi a presença de pelo menos um histórico de atraso igual ou superior a 60 dias, conforme descrito no notebook 1.
A escolha foi feita considerando que pequenos atrasos são volateis e costumam ser regularizados brevemente e atrasos maiores possuem maior risco de não chegarem a ser pagos em algum momento.

## 3. Normalização / padronização

Será realizada por meio de StandardScaler devido às variáveis numéricas contínuas, como a renda, que inclusive possui presença direta de outliers e poderia ser comprimida no caso do uso de MinMaxScaler.

O ajuste será realizado depois da divisão dos dados para treino.

## 4. Feature engineering

**Justificativa:** _preencher._

In [ ]:
# novas variáveis derivadas

## 5. Salvar dataset tratado

In [ ]:
PROCESSED.mkdir(parents=True, exist_ok=True)
df.to_csv(PROCESSED / "dataset_tratado.csv", index=False)